### ISSUE TITLE
Installing kivymd

### ISSUE THREAD

**Issue by quitegreensky** [kivymd/KivyMD#109]
Hello! 
Why do we have to install kivymd and then clone it to buildozer.spec requirements? can't we actually just put kivymd folder in our main directory and import it to our project? what's the differences between these two?

**Comment by andreisima** [comment]
You just change where KivyMD is located on mobile device.
If you use first method the KivyMD is seen as a dependency and installed in global python env on mobile device.
If you use second method KivyMD is seen as code and will be located in your project folder.

First method is more convenient since you only have to specify dependency and paths,  links and files will be taken care off under the hood.
Second method might require some folders and files to be manually included in buildozer.spec

**Comment by HeaTTheatR** [comment]
You can just put the library in your project.
