### ISSUE TITLE
MDFileManager problem

### ISSUE THREAD

**Issue by HeaTTheatR** [kivymd/KivyMD#1177]
Hi there! I started a private opensource project with KivyMD a few weeks ago. I really like it although I usually have trouble with GUI programming. Thanks a lot for your work! 

Today I came across a problem I couldn't solve yet. When I use the `MDFileManager` there seems to be problem when I try to follow logical links. The directories which are pointed to by the links are correctly displayed in the list. However, when I try to descend into them the click is simply ignored. What am I doing wrong? Thanks a lot!

_Originally posted by @marcus67 in https://github.com/kivymd/KivyMD/discussions/1077#discussioncomment-2117381_

**Comment by HeaTTheatR** [comment]
@marcus67
Attach a minimal code example that reproduces what you write about.

**Comment by marcus67** [comment]
It's really embarrassing, but I found out what the problem was. Apparently, it had nothing to do with being a normal directory or a symbolic link but with how I tried to click the sub directory. I always avoid clicking on the file / directory names but instead click on the folder icons themselved. In the FileManager the icons don't have any function at all. You have to click on the names. I got confused. I apologize for the disturbance.
