### ISSUE TITLE
MDToolbar

### ISSUE THREAD

**Issue by dertefter** [kivymd/KivyMD#1222]
Trying to use MDTopAppBar, and getting error:
'''
File "C:\(My directory)\venv\lib\site-packages\kivymd\uix\menu\menu.py", line 950, in ajust_radius
     firt_data_item = self.items[0]
 IndexError: list index out of range
'''

* OS: Windows 11
* Python: 3.9
* Kivy: 2.1.0
* KivyMD: 1.0.0

**Comment by HeaTTheatR** [comment]
@dertefter It looks like your issue doesn't match the template we made for you. Please review this template and create a new issue so that we can help you solve it.

![Снимок экрана 2022-04-05 в 16 11 11](https://user-images.githubusercontent.com/16930280/161761497-e727f631-b3ee-4add-a844-883b4ad9f4f8.png)
