### ISSUE TITLE
MDNavigationDrawer standard type animation source code

### ISSUE THREAD

**Issue by NightFurySL2001** [kivymd/KivyMD#1497]
In https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/#kivymd.uix.navigationdrawer.navigationdrawer.MDNavigationDrawer.type the demo shows a standard MDNavigationDrawer that opens and pushes the whole screen to the right. However I am unable to reproduce the same result. Is there any sample code for the demonstrated picture shown?

_Originally posted by @NightFurySL2001 in https://github.com/kivymd/KivyMD/discussions/1077#discussioncomment-5753435_

**Comment by HeaTTheatR** [comment]
How to create a Minimal, Reproducible Example
---------------------------------------------

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This is referred to by community members as creating a minimal, reproducible example (reprex), a minimal, complete and verifiable example (mcve), or a minimal, workable example (mwe). Regardless of how it's communicated to you, it boils down to ensuring your code that reproduces the problem follows the following guidelines:

Your code examples should be:
-----------------------------

1. Minimal – Use as little code as possible that still produces the same problem
2. Complete – Provide all parts someone else needs to reproduce your problem in the question itself
3. Reproducible – Test the code you're about to provide to make sure it reproduces the problem

The rest of this help article provides guidance on these aspects of writing a minimal, reproducible example.

Minimal
-------

The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.

2.Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Minimal and readable
--------------------

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code. Also, use spaces instead of tabs – tabs might not get correctly formatted on Stack Overflow.

Complete
--------

Make sure all information necessary to reproduce the problem is included in the question itself.

DO NOT use images of code. Copy the actual text from your code editor, paste it into the question, then format it as code. This helps others more easily read and test your code.

Reproducible
------------

To help you solve your problem, others will need to verify that it exists:

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

### Description of the Bug

Your text


### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```


### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here


### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by NightFurySL2001** [comment]
![image](https://raw.githubusercontent.com/HeaTTheatR/KivyMD-data/master/gallery/kivymddoc/navigation-drawer-standard.gif)
The animation referenced in the docs. There are no explaination on how to do this animation in https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/#kivymd.uix.navigationdrawer.navigationdrawer.MDNavigationDrawer.type

**Comment by HeaTTheatR** [comment]
I don't see any problems.

**Comment by NightFurySL2001** [comment]
Is it possible to provide a source code for how to achieve this animation? I tried to recreate the animaion using the minimal example provided in docs and could not achieve the animation as shown in the GIF.


```py

from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.scrollview import MDScrollView
from kivy.properties import ObjectProperty

KV = """
#: import MDFadeSlideTransition kivymd.uix.transition.transition.MDFadeSlideTransition

MDBoxLayout:
    orientation: "horizontal"
        
    MDNavigationDrawer:
        size_hint_x: None
        id: nav_drawer
        type: "standard"
        status: "opened"
        state: "open"
        radius: (0, 16, 16, 0)
        pos_hint: {"top": 1}

        ContentNavigationDrawer:
            screen_manager: screen_manager
            nav_drawer: nav_drawer


    MDBoxLayout:
        orientation: "vertical"
        size_hint_x: 1
        MDTopAppBar:
            pos_hint: {"top": 1}
            elevation: 4
            title: "MDNavigationDrawer"
            left_action_items: [["menu", lambda x: nav_drawer.set_state("toggle")]]
        
        MDScreen:
            MDScreenManager:
                id: screen_manager
                transition: MDFadeSlideTransition()
                
                MDScreen:
                    name: "scr 1"

                    MDLabel:
                        text: "Screen 1"
                        halign: "center"

                MDScreen:
                    name: "scr 2"

                    MDLabel:
                        text: "Screen 2"
                        halign: "center"

<ContentNavigationDrawer>

    MDList:

        OneLineListItem:
            text: "Screen 1"
            on_press:
                root.screen_manager.current = "scr 1"

        OneLineListItem:
            text: "Screen 2"
            on_press:
                root.nav_drawer.set_state("close")
                root.screen_manager.current = "scr 2"
"""

class ContentNavigationDrawer(MDScrollView):
    screen_manager = ObjectProperty()
    nav_drawer = ObjectProperty()

class Example(MDApp):
    def build(self):
        self.theme_cls.primary_palette = "Orange"
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)


Example().run()
```

**Comment by HeaTTheatR** [comment]
Please read the tips on how to create a issue correctly - https://github.com/kivymd/KivyMD/issues/1497#issuecomment-1534855719

**Comment by NightFurySL2001** [comment]
KivyMD: 1.1.1
Kivy: 2.1.0
OS: Windows 10
Python: 3.10.5

I would like to recreate this animation as provided by the documentation in https://kivymd.readthedocs.io/en/1.1.1/components/navigationdrawer/#kivymd.uix.navigationdrawer.navigationdrawer.MDNavigationDrawer.type .
![image](https://raw.githubusercontent.com/HeaTTheatR/KivyMD-data/master/gallery/kivymddoc/navigation-drawer-standard.gif)

My minimal code to implement the picture is:
```py
from kivy.lang import Builder
from kivymd.app import MDApp
from kivymd.uix.scrollview import MDScrollView
from kivy.properties import ObjectProperty

KV = """
#: import MDFadeSlideTransition kivymd.uix.transition.transition.MDFadeSlideTransition

MDBoxLayout:
    orientation: "horizontal"
        
    MDNavigationDrawer:
        size_hint_x: None
        id: nav_drawer
        type: "standard"
        status: "opened"
        state: "open"
        radius: (0, 16, 16, 0)
        pos_hint: {"top": 1}

        ContentNavigationDrawer:
            screen_manager: screen_manager
            nav_drawer: nav_drawer


    MDBoxLayout:
        orientation: "vertical"
        size_hint_x: 1
        MDTopAppBar:
            pos_hint: {"top": 1}
            elevation: 4
            title: "MDNavigationDrawer"
            left_action_items: [["menu", lambda x: nav_drawer.set_state("toggle")]]
        
        MDScreen:
            MDScreenManager:
                id: screen_manager
                transition: MDFadeSlideTransition()
                
                MDScreen:
                    name: "scr 1"

                    MDLabel:
                        text: "Screen 1"
                        halign: "center"

                MDScreen:
                    name: "scr 2"

                    MDLabel:
                        text: "Screen 2"
                        halign: "center"

<ContentNavigationDrawer>

    MDList:

        OneLineListItem:
            text: "Screen 1"
            on_press:
                root.screen_manager.current = "scr 1"

        OneLineListItem:
            text: "Screen 2"
            on_press:
                root.nav_drawer.set_state("close")
                root.screen_manager.current = "scr 2"
"""

class ContentNavigationDrawer(MDScrollView):
    screen_manager = ObjectProperty()
    nav_drawer = ObjectProperty()

class Example(MDApp):
    def build(self):
        self.theme_cls.primary_palette = "Orange"
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)


Example().run()
```

However, on clicking the menu button, the menu retracts but there is an empty space left, unlike in the GIF where the app bar and screen is pushed to the left and fill up the screen.
![image](https://user-images.githubusercontent.com/33471049/236241425-5def91eb-ed9a-4ee9-aa6e-b4ff077c1601.png)

I tried to resolve it with `size_hint_x: None` for MDNavigationDrawer and `size_hint_x:1` for the MDBoxLayout to the right. I also tried resolving it by using MDGridLayout, `cols:2` on the top instead of MDBoxLayout for the root widget.

As the GIF demonstrated it is definitely possible to implement this, but I could not find how to do it.

**Comment by HeaTTheatR** [comment]
```python
from kivy.lang import Builder

from kivymd.uix.boxlayout import MDBoxLayout
from kivymd.app import MDApp

KV = '''
MDScreen:

    MDNavigationLayout:

        MDScreenManager:

            MDScreen:

                MDTopAppBar:
                    title: "Navigation Drawer"
                    elevation: 4
                    pos_hint: {"top": 1}
                    md_bg_color: "#e7e4c0"
                    specific_text_color: "#4a4939"
                    left_action_items:
                        [['menu', lambda x: nav_drawer.set_state("toggle")]]


        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)
            type: "standard"

            ContentNavigationDrawer:
'''


class ContentNavigationDrawer(MDBoxLayout):
    pass


class Example(MDApp):
    def build(self):
        self.theme_cls.theme_style = "Dark"
        return Builder.load_string(KV)


Example().run()
```

**Comment by NightFurySL2001** [comment]
Thank you!

**Comment by NightFurySL2001** [comment]
It might be better if the documentation can include such information (using MDNavigationLayout for sliding standard Navigation Drawer). Maybe I'll find time to add the docs.
