### ISSUE TITLE
MDFloatingActionButtonSpeedDial fast close-open causes the floating buttons to disappear

### ISSUE THREAD

**Issue by UriyaHarpeness** [kivymd/KivyMD#1578]
### Description of the Bug

When closing and re-opening the floating action button, the child buttons disappear.
I assume it's because the closing animation didn't finish completely, and the animations conflict with each other.
But, I'm leaving it to the experts, thanks.

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.button import MDFloatingActionButtonSpeedDial
from kivymd.uix.screen import MDScreen


class ExampleApp(MDApp):
    def build(self) -> MDScreen:
        return MDScreen(
            MDFloatingActionButtonSpeedDial(
                id="speed_dial",
                root_button_anim=True,
                icon="heart-plus",
                data={
                    "Heart": "heart"
                },
            )
        )


if __name__ == "__main__":
    ExampleApp().run()
```

### Screenshots

<img width="312" alt="image" src="https://github.com/kivymd/KivyMD/assets/53301931/aa8e98d6-27b7-4876-a680-f415f79c2028">

<img width="312" alt="image" src="https://github.com/kivymd/KivyMD/assets/53301931/5b7c6d6e-66a7-4383-aac9-2aed3285924d">

### Versions

* OS: MacOS
* Python: 3.11.5
* Kivy: 2.2.1
* KivyMD: 1.1.1

**Comment by HeaTTheatR** [comment]
This widget has been removed from the KivyMD 2.0.0 library

**Comment by UriyaHarpeness** [comment]
Oh, sorry to hear that I assume, I'll close the issue.
Does it have a successor?
And when is the new version scheduled to be published?

**Comment by HeaTTheatR** [comment]
Version 2.0.0 is still under active development, but today you can testing the work done. Clone the repository https://github.com/kivymd/KivyMD/tree/2.0.0 go to the examples - https://github.com/kivymd/KivyMD/tree/2.0.0/examples folder and test the code examples 🧐 It will also be useful for learning the new API, since you all know that version 2.0.0 will be conflicting  with the previous versions of the KivyMD library. 

Most likely, the MDFloatingActionButtonSpeedDial widget will be distributed as separate additional modules

**Comment by HeaTTheatR** [comment]
https://www.youtube.com/watch?v=MiDpAFbgs60

**Comment by UriyaHarpeness** [comment]
Thanks.
