### ISSUE TITLE
Problem with MDToolbar

### ISSUE THREAD

**Issue by mozesa** [kivymd/KivyMD#190]
#### Description of the Bug

**Hi all**,

First of all I would like to express my thankfulness for your work!
It is really good!

My problem is that there is some color glitch in case of MDToolbar.
Please, see the screenshot attached.

Thanks for your help in advance.

Best Regrads!

### Code and Logs

```python
from kivy.lang import Builder

from kivymd.app import MDApp

KV = '''
BoxLayout:
    orientation: "vertical"

    MDToolbar:
        title: "MDToolbar"

    MDLabel:
        text: "Content"
        halign: "center"
'''


class Test(MDApp):
    def build(self):
        return Builder.load_string(KV)


Test().run()
```

### Screenshots
![image](https://user-images.githubusercontent.com/49973426/75477724-095c4180-599d-11ea-9079-2189573c8571.png)

### Versions

* OS:  Windows 10
* Python: v3.8.1
* Kivy: v2.0.0rc1, git-ae0fa0c, 20191229
* KivyMD:  v0.103.0

**Comment by ArtemSBulgakov** [comment]
Hi. Thank you for your issue!

In version 0.103.0 MDToolbar has invisible background and you need to add background color to your toolbar.
```md_bg_color: app.theme_cls.primary_color```

It is fixed in master branch. You can install it (see readme) and default color of MDToolbar will be the primary theme color.

Feel free to add comments if your problem wasn't solved.
