### ISSUE TITLE
 MDTabs,MDTabsBase  and Kivy 2.0.0rc3

### ISSUE THREAD

**Issue by RobertFlatt** [kivymd/KivyMD#359]
### Description of the Bug

Using KivyMD 1.104.1

2.0.0rc2 the example below gives:
`[WARNING] [ColorParser ] Invalid color format for '#'`

2.0.0rc3 the example below gives:

```
Traceback (most recent call last):
  File "C:\Users\Bobf\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 701, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 527, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 2023, in kivy.properties.ColorProperty.convert
ValueError: MDTabsLabel.color must have 3 or 4 components (got [])

```
Also filed here  https://github.com/kivy/kivy/issues/6957

### Code and Logs

```python
from kivymd.app import MDApp
from kivymd.uix.tab import MDTabs,MDTabsBase
from kivymd.uix.boxlayout import MDBoxLayout

class Tab(MDBoxLayout, MDTabsBase):
    def __init__(self, **kwargs):
        super(Tab, self).__init__(**kwargs)
        pass
    
class MyApp(MDApp):

    def build(self):
        t = MDTabs()
        b = Tab(text='foo')   # Issue here
        return t

if __name__ == '__main__':
    MyApp().run()
```

### Versions

* OS:   Windows 10
* Python:  2.8.2
* Kivy:  2.0.0rc3
* KivyMD:  1.104.1

**Comment by HeaTTheatR** [comment]
@Ham-Merhead Try`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by RobertFlatt** [comment]
It is downloading Kivy 1.11.1 which seems wrong.
Then it fails because it wants me to install Visual C++, not just the runtime.

**Comment by HeaTTheatR** [comment]
Fix https://github.com/HeaTTheatR/KivyMD/commit/f0c64aeeb467f1057809d408879c6d314a4cddfb

**Comment by RobertFlatt** [comment]
Confirmed fixed with Kivy 2.0.0rc3 . Thank you.

**Comment by ysma500** [comment]
First of all, I might be wrong considering it's my first time doing UI on python. But his error seems to have creep back up because I'm using the [Tabs_Example](https://kivymd.readthedocs.io/en/latest/components/tabs/#example-with-tab-text) from the rtd as-is and still got this wonderful error: 
![image](https://user-images.githubusercontent.com/32311542/110269413-a3cc6900-7f91-11eb-9d75-e7f25be474d5.png)

here are my versions in my requirements.txt:
On windows 10, using Anaconda pkg manager and python 3.8.8
certifi==2020.12.5
chardet==4.0.0
docutils==0.16
idna==2.10
Kivy==2.0.0
kivy-deps.angle==0.3.0
kivy-deps.glew==0.3.0
kivy-deps.gstreamer==0.3.1
kivy-deps.sdl2==0.3.1
Kivy-Garden==0.1.4
kivymd==0.104.1
Pillow==8.1.2
Pygments==2.8.1
pypiwin32==223
pywin32==300
requests==2.25.1
urllib3==1.26.3
wincertstore==0.2

**Comment by HeaTTheatR** [comment]
@ysma500 Use KivyMD library from master branch.

**Comment by ysma500** [comment]
@HeaTTheatR  When I pull using pip I use what branch?

**Comment by HeaTTheatR** [comment]
@HeaTTheatR No. `pip install https://github.com/kivymd/KivyMD/archive/master.zip`

**Comment by ysma500** [comment]
@HeaTTheatR Thank you, will try that tomorrow 😊... Will it ever be versionned and pushed to pypi?
