### ISSUE TITLE
Include default set of Fonts

### ISSUE THREAD

**Issue by rubengerad** [kivymd/KivyMD#470]
### Description of the Feature

The choice of available default set of fonts is limited to one, though it is easy to add new fonts, it would be great to have a default set included, perhaps google fonts?

**Comment by ArtemSBulgakov** [comment]
You can replace default font by modifying `ThemeManager.font_styles`.
Do you mean adding more fonts to KivyMD package? I think it is not very good idea because fonts will increase .apk size.

**Comment by rubengerad** [comment]
Thanks for your reply, I already downloaded a few, but would it be too
heavy to add a few fonts?  Atleast the option of a different header font
and sub title and normal font would be great and the option of referencing
online font library.

**Comment by podraco** [comment]
that would mean that it will need to download resources from internet and be stored somewhere in the device, i'm not sure if the android polices would allow something like that easily and generic for every device...

**Comment by ArtemSBulgakov** [comment]
@rubengerad To change font for one MDLabel, you can set `font_style: "Custom"` and `font_name` as for Kivy Label. To change font for all MDLabel widgets with the same `font_style` you should change `font_styles` dictionary in ThemeManager.

@podraco On Android app has its own folder. You can use that folder to download or store anything without using sdcard.

It's not safe to download fonts from internet because user may use your app offline or URL may be broken. So developer should include all resources to .apk package.
