### ISSUE TITLE
MDTextField's hint_text cant be set outside of kv language

### ISSUE THREAD

**Issue by DaedlyKitten** [kivymd/KivyMD#493]
![Snip1314549875](https://user-images.githubusercontent.com/45991388/91526598-98d7b280-e936-11ea-95f0-6624b40dafcd.png)

```python
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager,Screen
from kivy.properties import ObjectProperty
from kivymd.app import MDApp
from kivymd.textfields import MDTextField
KV = '''

<aaa>   
    t1:t1
    BoxLayout:
        id:t1
        MDTextField:
            hint_text:'aaaa'
            text:'text1'
'''

class aaa(Screen):
    t1=ObjectProperty()
    def __init__(self, **kwargs):
        super().__init__(**kwargs)    
        self.t1.add_widget(MDTextField(hint_text='aaaa',text='text2'))

class Test(MDApp):
    def build(self):
        Builder.load_string(KV)
        self.screen=aaa()
        return self.screen


Test().run()
```

This is a sample code of 2 text fields, only the first one's 'hint_text' can be set, the other one will not have hint text, helper_text, anything other than 'text' itself wont work...

**Comment by DaedlyKitten** [comment]
Also I cant see any cursor on the text field.

Win10, 
latest version of everything

**Comment by podraco** [comment]
i can confirm that this bug has 2 main problems
1. The properties are not used from the `__init__` kwargs, this means that the class has no way to update it's content after a new instance is created. This may be solved using the clock.schedule_once calling a function to read and evaluate all properties

1. The animation of the hint_text doesnot work correctly when the label instance has already a text inside. this menas that the hit text will keep it's normal size instead of shrinking down

For now, the bug may be bypassed byt updating the widget after the instace is created

```py
def __init__(self, **kwargs):
    super().__init__(**kwargs)    
    X=MDTextField(
        hint_text='asdasdasd',
        text='text2'
        )
    self.t1.add_widget(X) 
    X.hint_text='aaaa' <- this will call the update event for the hint text.
```
