### ISSUE TITLE
MDTextFIeld bug

### ISSUE THREAD

**Issue by allexeyj** [kivymd/KivyMD#571]
### Description of the Bug

If u don't wanna read description of the bug or u don't understand me, see this video(https://yadi.sk/i/oYdoLvBIp4tN6Q), all bugs were shown in this video

I have a code that located below.
At first, i edited field's text to 'hhh' and pressed on my button, as the result, i got new normal text of my field without any bugs.
But after that, i had held backspace until field's text is equal to empty string(''), and then i pressed on my button.
And after that i got a strange behavior. See screenshot below.

### Code and Logs

```python
from kivy.lang import Builder
from kivymd.app import MDApp


KV = '''
Screen:
    MDRaisedButton:
        text: 'update field text'
        pos_hint: {'center_y': .5, 'center_x': .5}
        on_release: app.change()
    MDTextField:
        id: field
        text: ''
        hint_text: 'Bug'
        pos_hint: {'center_y': .7, 'center_x': .5}
'''


class Test(MDApp):
    def change(self):
        self.root.ids.field.text = 'New text'

    def build(self):
        return Builder.load_string(KV)


Test().run()

```

### Screenshots

![Test 06 10 2020 13_41_32](https://user-images.githubusercontent.com/71039746/95191736-d3f0bf80-07d9-11eb-96ce-2aa0f07cf6f1.png)

### Versions

* OS: win10
* Python: 3.7
* Kivy: last version
* KivyMD: master branch.

**Comment by shashi278** [comment]
@alexcode4u I'm not sure if we should categorize it as a bug exactly because you're not using the text field as it's intended to be used( by typing into it). I'll wait for others to comment.
This behavior is expected as clicking outside the text field( in this case pressing the button) unfocuses the text field which then shows the placeholder text but at the same time, you're changing `text` attribute which will bring it over the placeholder text.

A quick fix is to handle the text field focus manually as well. Add an extra line to your `change` method:
```python
self.root.ids.field.focus = True
```

**Comment by allexeyj** [comment]
Thank u. It has resolved my problem, but i also will be waiting for others comments, i won't close issue
