### ISSUE TITLE
MDFIleManager doesn't work if ext property is not provided

### ISSUE THREAD

**Issue by tksundar** [kivymd/KivyMD#593]
### Description of the Bug
Metadata-Version: 2.1
Name: kivymd
Version: 0.104.1

MDFileManager: 

When using the following code
 ```
 self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
            ext=['.xlsx', '.pdf']
        )
```
the extensions are not honored as the code overrides this in the init method so:
`self.ext = [".png", ".jpg", ".jpeg"]`

As such it never shows any other file type. I had to hack it with the following code to make it work for other file types
```
  self.file_manager = MDFileManager(
            exit_manager=self.exit_manager,
            select_path=self.select_path,
        )
        self.file_manager.ext = ['.xlsx', '.pdf'] 

```
With this it allows selection of pdf or xlsx files 

### Code and Logs

```python
from kivy.app import App
from kivy.lang import Builder

kv = """
Screen:
    # KV-Code
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

### Screenshots

Add images to explain us this bug. Paste urls here.

Remove this section if no images here

### Versions

* OS: 
* Python: 
* Kivy: 
* KivyMD:

**Comment by shashi278** [comment]
Hi @tksundar, please provide a working example so that we can verify your issue.

**Comment by tksundar** [comment]
I have verified that my hack works. It just one line of code that I have mentioned in the bug description.

**Comment by HeaTTheatR** [comment]
@tksundar Reinstall KivyMD library from master branch:

![Снимок экрана 2020-10-23 в 06 35 53](https://user-images.githubusercontent.com/16930280/96953589-1ca6b900-14fa-11eb-9535-d0f4e40a03ee.png)

**Comment by janandaj** [comment]
If I use android api version as 30 in buildozer spec, after the build file filtering based on extension does not work. If i choose the android api version as 27 in builozer spec, everything works fine. No any code changes. only the change in buildozer file
from
#android.api = 30(does not work)
to
#adndroid.api = 27 (does work)

used the master code branch as well in the spec file. but there is no success.
#requirements = kivy==2.1.0, https://github.com/kivymd/KivyMD/archive/master.zip

I just want to select json files from MDFileManger and I tried all the solutions above without success.
#self.file_manager.ext  = ['.json','.JSON']

I tested the build on Samsung A21s with Android 11.

Can someone please help because without building the android apk using android api level 30, it cannot be uploaded to google play store. It asks minimum level to be 30

**Comment by Osmar-Souza** [comment]
você conseguiu resolver esse problema @janandaj ?

**Comment by janandaj** [comment]
> você conseguiu resolver esse problema @janandaj ?

**Comment by janandaj** [comment]
> você conseguiu resolver esse problema @janandaj ?

issue is not fixed

**Comment by HeaTTheatR** [comment]
@janandaj The issue is closed so it has been fixed for a long time and works fine.
