### ISSUE TITLE
MDInputDialog not displaying correctly on android landscape orientation

### ISSUE THREAD

**Issue by ocobacho** [kivymd/KivyMD#71]
On android MDInputDialog shows ok on portrait orientation but in landscape the label of the input gets out of the dialog.

**Comment by Jonatanjrss** [comment]
@ocobacho, I ran the sample code that has inside the dialog.py file of the kivymd source code and I got the same problem as you. However I realized that the problem is not in MDInputDialog. I believe that when creating the MDInputDialog you are passing `size_hint = (.8, .4)` to it, if you pass `size_hint = (.8, .5)` or `size_hint = (.8, .6)`instead your problem will be solved, at least it worked for me.
