### ISSUE TITLE
Can't we exclude GPL and LGPL from all dependencies?

### ISSUE THREAD

**Issue by MKdays** [kivymd/KivyMD#786]
Kivymd is the most ideal framework I've ever seen. But

https://github.com/kivymd/KivyMD/blob/72d758ed30152e2c1c7222afe52d43681d27a36f/LICENSE#L18

The above module is LGPL license.
Kivymd can maintain MIT because it is in source code state, but if it is created as an EXE file, it will not comply with LGPL.
For businesses and those who want exclusive licenses, LGPL is reluctant due to possible legal issues.
That's my only concern.

Can't we exclude GPL and LGPL from all dependencies?

**Comment by HeaTTheatR** [comment]
@MKdays Thanks for the information. I will rewrite this module in the near future. So the `KivyMD` library will no longer be bound by the `LGPL` license.

**Comment by podraco** [comment]
How about creating a launcher for your app?

**Comment by HeaTTheatR** [comment]
@podraco Unfortunately, I didn't understand what you mean...

**Comment by podraco** [comment]
ideally, you would spread the Runtime environment that will be open source from the privative code. this way the open sourced code will only launch your program as a different lib, it also allows you to make changes before the actual program starts :P and also allows you to make the program lighter. since kivyMD will be used as a lib without any modifications.

**Comment by HeaTTheatR** [comment]
@podraco https://github.com/kivy/kivy-launcher
