### ISSUE TITLE
Shadow Elevation is not balanced on android

### ISSUE THREAD

**Issue by kengoon** [kivymd/KivyMD#845]
### Description of the Bug

On android shadow is not balanced, it is onesided (to the right)

Before![Screenshot_20210213-064821.png](https://user-images.githubusercontent.com/42192162/107843009-ce2e6a80-6dc7-11eb-8641-a757e42f3fdc.png)

After

https://user-images.githubusercontent.com/42192162/107843094-72b0ac80-6dc8-11eb-8f27-d806d1ef1e0a.mp4

### Versions

* OS: android
* Python: 3.8
* Kivy: 2.0.0
* KivyMD: master

**Comment by podraco** [comment]
Unless you have set a custom origin to the shadow, it should be centered, a little below the widget. how is defined the kv?

**Comment by kengoon** [comment]
I did not set any custom origin on the shadow.

I just defined a normal MDCard like this:

```yaml
MDCard:
    elevation: 10
    orientation: "vertical"

**Comment by podraco** [comment]
Quick update, half my country has no electricity supply ( specially my city), 
the authorities say that there would be Rotary shutdowns, because of that, i get electricity every now and then, so i won't be able to check on this in the near future. As soon as everything goes back to normal I'll check the behavior.

**Comment by HeaTTheatR** [comment]
Fix in master branch.
